
name: Update Dependencies in README

on:
  workflow_call:
    inputs:
      java_version:
        description: "The Java version to use"
        required: false
        type: string
        default: "17"

jobs:
  update_readme_dependencies:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java_version }}
          distribution: 'zulu'
          cache: maven

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Update dependencies in README
        run: |
          python .github/scripts/update-dependecies-in-readme.py

      - name: Check if file was changed
        run: |
            if git diff --name-only | grep -e 'README.md'; then
              echo "The file was changed"
              echo "was_file_changed=true" >> "$GITHUB_ENV"
            else
              echo "The file was not changed"
              echo "was_file_changed=false" >> "$GITHUB_ENV"
            fi

      - name: Create pull request
        if: ${{ env.was_file_changed == 'true' }}
        uses: peter-evans/create-pull-request@v6
        with:
          add-paths: |
            README.MD
          token: ${{ secrets.ECSP_BOT_PAT }}
          branch: chore/update-readme-dependencies
          commit-message: "chore(readme): Update DEPENDENCIES in README"
          delete-branch: true
          title: Update DEPENDENCIES in README
          body: |
            This PR updates the DEPENDENCIES in the README file.
    